trigger:
- main

pool:
  vmImage: windows-latest

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  name: 'NuGetToolInstaller'
  displayName: 'NuGet Install'

- task: NuGetCommand@2
  name: 'NuGetRestore'
  displayName: 'NuGet Restore Packages'
  inputs:
    command: 'restore'

- task: DotNetCoreCLI@2
  name: 'Tests'
  displayName: 'Run Tests'
  inputs:
    command: 'test'
    arguments: '--configuration $(BuildConfiguration)'
  
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true
  displayName: 'Publish'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)' 
    artifactName: drop
  displayName: 'Upload Artifact'
